In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
Data = pd.read_csv("WorldCupMatches.csv")
Data.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [13]:
keep_columns = ["Year","Stage","Home Team Name","Home Team Goals", "Away Team Goals", "Away Team Goals","Attendance"]
Val = Data[Data.columns.intersection(keep_columns)].dropna()
Val

,Year,Stage,Home Team Name,Home Team Goals,Away Team Goals,Attendance
0,1930.0,Group 1,France,4.0,1.0,4444.0
1,1930.0,Group 4,USA,3.0,0.0,18346.0
2,1930.0,Group 2,Yugoslavia,2.0,1.0,24059.0
3,1930.0,Group 3,Romania,3.0,1.0,2549.0
4,1930.0,Group 1,Argentina,1.0,0.0,23409.0
...,...,...,...,...,...,...
847,2014.0,Quarter-finals,Netherlands,0.0,0.0,51179.0
848,2014.0,Semi-finals,Brazil,1.0,7.0,58141.0
849,2014.0,Semi-finals,Netherlands,0.0,0.0,63267.0
850,2014.0,Play-off for third place,Brazil,0.0,3.0,68034.0
851,2014.0,Final,Germany,1.0,0.0,74738.0

In [14]:
print(pd.unique(Val["Home Team Name"]))
print(pd.unique(Val["Stage"]))

['France' 'USA' 'Yugoslavia' 'Romania' 'Argentina' 'Chile' 'Uruguay'
 'Brazil' 'Paraguay' 'Austria' 'Hungary' 'Switzerland' 'Sweden' 'Germany'
 'Spain' 'Italy' 'Czechoslovakia' 'Cuba' 'England' 'Germany FR' 'Turkey'
 'Soviet Union' 'Northern Ireland' 'Mexico' 'Wales' 'Portugal' 'Korea DPR'
 'Peru' 'Belgium' 'Bulgaria' 'German DR' 'Zaire' 'Poland' 'Australia'
 'Scotland' 'Netherlands' 'Haiti' 'Tunisia' 'Algeria' 'Honduras' 'Canada'
 'Morocco' 'Korea Republic' 'Iraq' 'Denmark' 'rn">United Arab Emirates'
 'Costa Rica' 'Cameroon' 'rn">Republic of Ireland' 'Colombia' 'Norway'
 'Nigeria' 'Saudi Arabia' 'Bolivia' 'Russia' 'Greece' 'Jamaica'
 'South Africa' 'Japan' 'Croatia' 'China PR' 'Senegal' 'Slovenia'
 'Ecuador' 'rn">Trinidad and Tobago' 'rn">Serbia and Montenegro' 'Angola'
 'Czech Republic' 'Togo' 'Iran' "C�te d'Ivoire" 'Ghana' 'Ukraine' 'Serbia'
 'New Zealand' 'Slovakia' 'IR Iran' 'rn">Bosnia and Herzegovina']
['Group 1' 'Group 4' 'Group 2' 'Group 3' 'Semi-finals' 'Final'
 'Preliminary round' 'Quarter-finals' 'Match for third place'
 'First round' 'Group 6' 'Group B' 'Group A' 'Group 5' 'Group C' 'Group D'
 'Group F' 'Group E' 'Round of 16' 'Group H' 'Group G' 'Third place'
 'Play-off for third place']

In [15]:
Val["Count"] = 0
One = ["Group 1","Group 2","Group 3","Group 4","Group 5","Group 6","Group A","Group B","Group C","Group D","Group E","Group F","Group G","Group H"]
Val.loc[Val["Stage"].isin(One),"Count"]=1
#TODO: Factor in both Home and Away Team

,Year,Stage,Home Team Name,Home Team Goals,Away Team Goals,Attendance,Count
0,1930.0,Group 1,France,4.0,1.0,4444.0,1
1,1930.0,Group 4,USA,3.0,0.0,18346.0,1
2,1930.0,Group 2,Yugoslavia,2.0,1.0,24059.0,1
3,1930.0,Group 3,Romania,3.0,1.0,2549.0,1
4,1930.0,Group 1,Argentina,1.0,0.0,23409.0,1
...,...,...,...,...,...,...,...
847,2014.0,Quarter-finals,Netherlands,0.0,0.0,51179.0,0
848,2014.0,Semi-finals,Brazil,1.0,7.0,58141.0,0
849,2014.0,Semi-finals,Netherlands,0.0,0.0,63267.0,0
850,2014.0,Play-off for third place,Brazil,0.0,3.0,68034.0,0
851,2014.0,Final,Germany,1.0,0.0,74738.0,0